server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ENC(SNtSOgu9DXFa98NXZZApP57X87SbGOQlCI2MkAKS/XLR6feP68CNr8yrx3z8txuck+Lg1dvdr2rPcm0plv/NUGJc2hRe0R+N2v7iPzYrhFi/L+dJ0YhKYg==)
    username: ENC(zuc9rYGxV0dXP101AWu5asaq14XpNZl7oJGN0so6k6RH6D/4MIEowA==)
    password: ENC(WuzgxtxpITkzbwKWlAkXyzQpc+vE/Y+CPJjcbxloxV8=)
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
      dialect: -- org.hibernate.dialect.PostgreSQLDialect

admin:
  univ-id: END(MnnJJNaW4by9rR1oo90AfA==)
  name: END(74r3AHMoJBHegbbayNVTRbM3GACH/df5)
  password: END(syprHyAFiPy50LqxoNeK5B3dPZ3g4tZdgslnAjARey8=)

# cors
origin:
  domain: ENC(oT5JIgnR3+8hZdo1yl3lwn7AwB+AZIinDX9Xnb0Fzss=)

logging:
  config: classpath:log4j2-prod.xml
