server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ENC(5zqShAjVmyJ2d45bahY29W9iJjjlaopZCiHWBQDmnGsysvfNPhV+8r1iA2w18NWLVUfctiS5Z4a/l3/QLay6MEIdE1DUkhsATbpZrDyy7lrHCGX/r2KxIhzEwE093+dadkERKLhDtIs=)
    username: ENC(97015VsffcgI0f3/4wkIRF83s66KSbgB)
    password: ENC(k9/r7urCpjm1zejJNalPZ+CnqEuf3b/r9t+66h8bZVw=)
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
      dialect: -- org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ENC(18FNZ6cjSHBH889DgERn3ZscMgAY8R02b6DBg9l47Xs=)
            client-secret: ENC(hUvBA0g45hgzXQ2Ia/ovO8dQWDR67BsVt6Um0h1cSh/qrwKaWdVND06XApXIJMSaZy5Kem6nJx4=)

admin:
  univ-id: END(MnnJJNaW4by9rR1oo90AfA==)
  name: END(74r3AHMoJBHegbbayNVTRbM3GACH/df5)
  password: END(syprHyAFiPy50LqxoNeK5B3dPZ3g4tZdgslnAjARey8=)

# cors
origin:
  domain: ENC(oT5JIgnR3+8hZdo1yl3lwn7AwB+AZIinDX9Xnb0Fzss=)

logging:
  config: classpath:log4j2-prod.xml
